### ISSUE TITLE
 error in Dubugdivision  

### ISSUE THREAD

**Issue by cyckun** [snwagh/falcon-public#10]
Hi, i find the division test result is error, everybody meet such problem?
In the test, a = 3.2 b=9.7, the result should be a / b = 0.32, but the code result is 0.0198, 
Is there some errors in my test?
![image](https://user-images.githubusercontent.com/52144640/127453049-01c9c9f7-9f47-4ebe-a430-b12607d7f092.png)

**Comment by snwagh** [comment]
I do believe that could be a result of the finite amount of precision in storing numbers. I think if the integer part is generally of this order (about 4 or beyond), the correctness would be affected. 

You can try 
- Increasing the bit-width by changing to [uint64_t](https://github.com/snwagh/falcon-public/blob/master/src/globals.h#L55)
- Reducing the [fixed-point precision](https://github.com/snwagh/falcon-public/blob/master/src/globals.h#L38)

**Comment by cyckun** [comment]
great，using uint64_t  solved my question, thanks you, snwagh.
