### ISSUE TITLE
A simple question about `funDotProduct` function

### ISSUE THREAD

**Issue by WeiViming** [snwagh/falcon-public#11]
Hello, @snwagh . I have a question about [this function](https://github.com/snwagh/falcon-public/blob/b227f78b92a9d5db5d8891f8b17b016d7d04ddef/src/Functionalities.cpp#L739). I guess it is used to compute the dot product between two vectors `a` and `b` , i.e. `ab=c`, where `c` is a number. However, this function requests `c.size() == size`. Is something wrong with it? Thank you!

**Comment by snwagh** [comment]
That is just poor naming on my part, the functionality implements component wise product: c[i] = a[i] b[i]

**Comment by WeiViming** [comment]
Oh, yes! Thank you for your help!
