### ISSUE TITLE
Functions in Precompute.cpp

### ISSUE THREAD

**Issue by imtiyazuddin** [snwagh/falcon-public#21]
As I understand, all the functions in Precompute.cpp (currently) are just initializing values to 0, can you give a one liner for these functions and how to re-write them ??

**Comment by snwagh** [comment]
If I understand your goals correctly, you want to re-randomize the values. For instance, in [this](https://github.com/snwagh/falcon-public/blob/master/src/Precompute.cpp#L85) example of generating a triple, you can (1) pick random values for `a`, `b` and then compute `c` as `a*b` and (2) Generate random shares for `a`, `b`, `c` so each party can receive their appropriate share. You might need to pass/use the partyNum (party identifier inside Precompute.cpp) to achieve this. Note that even with this implementation, it is not secure for multiple reasons (main one, the randomness is generated on a single executable).

**Comment by imtiyazuddin** [comment]
Ok, will look into it
