### ISSUE TITLE
How to generate the common randomness in functionality wrap3?

### ISSUE THREAD

**Issue by Linstar-L** [snwagh/falcon-public#24]
Hello! I read the paper Falcon: Honest-Majority Maliciously Secure Framework for Private Deep Learning. I wonder how to generate the common randomness in Algorithm wrap3, which I didn't find in code, i.e the shares of a random number x and the shares of the carry bit.

**Comment by snwagh** [comment]
Hi, the preloading component of the code is not implemented. The pseudo code is provided in the Fig. 6 [here](https://arxiv.org/pdf/2004.02229.pdf), it may not be the most optimal method but it should work (starting with shares of bits and then using share conversion algorithms).

**Comment by Linstar-L** [comment]
Thank you. I wonder how to implement FA to compute the carry bit of the random shares.

**Comment by snwagh** [comment]
Take a look at Section 4 of [this](https://faui1-files.cs.fau.de/filepool/publications/octavian_securescm/SecureSCM-D.9.2.pdf).

**Comment by Linstar-L** [comment]
Thank you for your help.
