### ISSUE TITLE
How to change the number of epochs when training networks 

### ISSUE THREAD

**Issue by khoaguin** [snwagh/falcon-public#44]
Hi, 

How can I define the number of training epochs for different networks? I have found that there is a variable named `NUM_ITERATIONS` in `main.cpp`, but not sure what it is, and also we cannot change it in `makefile` either.

Thank you.

**Comment by snwagh** [comment]
The variable is set `src/globals.h` so you can change it there.

**Comment by khoaguin** [comment]
I tried to change the variable `NO_OF_EPOCHS` to different values, but nothing really happened

**Comment by khoaguin** [comment]
From the `train` function, I think that the `NUM_ITERATIONS` variable is actually the number of epochs to train the neural network. Am I wrong? 

![Screenshot from 2022-07-05 10-12-37](https://user-images.githubusercontent.com/88959106/177242267-620b0983-8f32-43eb-9e6b-46dee41f8141.png)

**Comment by snwagh** [comment]
So the codebase is designed to use `NUM_ITERATIONS` only, if you want to set using the number of epochs, you comment out [this line](https://github.com/snwagh/falcon-public/blob/master/src/globals.h#L49) and uncomment [this line](https://github.com/snwagh/falcon-public/blob/master/src/globals.h#L50).
