### ISSUE TITLE
Question about  falcon-public/tree/master/MNIST

### ISSUE THREAD

**Issue by zewen-s** [snwagh/falcon-public#47]
hi. I tried to download and parse the MNIST dataset on falcon-public/MNIST/ , and I got the results like it. I have searched the Internet for this error. Some people say that it is because the parameter in the stoi function is not a string that can be converted into an integer.
![Screenshot](https://user-images.githubusercontent.com/80888328/193448149-7f7127a3-0e35-4944-a53f-f26bf846341d.png)

Can someone help me solve this problem？

**Comment by zewen-s** [comment]
hi. I tried to download and parse the MNIST dataset on  falcon-public/MNIST/ , and I got the results like it. I have searched the Internet for this error. Some people say that it is because the parameter in the stoi function is not a string that can be converted into an integer.
![Screenshot](https://user-images.githubusercontent.com/80888328/193447821-9c10ae1c-08ab-44b9-a715-8c1857da8b0b.png)

 Can someone help me solve this problem？

**Comment by zewen-s** [comment]
I have another question. Even though I don't have a mnist dataset, I can still run it with the make terminal command?As shown in the picture below
![Screenshot 2](https://user-images.githubusercontent.com/80888328/193448413-850a427c-1e37-4594-854b-b84d3b6ba3a4.png)

**Comment by zewen-s** [comment]
I have solved the above problems by trying, thanks

**Comment by dorafan** [comment]
> I have solved the above problems by trying, thanks

Hi, I also have the same question. Would you mind sharing your thoughts?
